<%@ Page Title="" Language="C#" MasterPageFile="~/Masterpage.Master" AutoEventWireup="true" CodeBehind="Sigin.aspx.cs" Inherits="RegisterPortal.Sigin" %>

<asp:Content ContentPlaceHolderId="CPH1" runat="server">
    <form runat="server">
            <section class="container">
                <div class="text-right">
        <div class="form-inline">
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <asp:Button ID="Button6" runat="server" class="btn btn-primary" Text="Logout" OnClick="Button6_Click"/>
            </div>
            </div>
            <section class="jumbotron">
          <div class="text-center">
          <h2><asp:Label ID="NotOk" class="alert alert-danger" role="alert" runat="server" Text="Virker dette her overhovedet" Visible="False"></asp:Label></h2>
          <h2><asp:Label ID="Ok" class="alert alert-success" role="alert" runat="server" Text="Virker dette her overhovedet" Visible="False"></asp:Label></h2>

          </div> 
          <h2 class="text-center">MATSUMAE CUP 2016</h2>
          <h4 class="text-center">Press the button below to register</h4>
        <p>
            <asp:Label ID="DoNotTouch" runat="server" Text="Label" Visible="False"></asp:Label>
            <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>

        </p>
        <center>
         <asp:TextBox ID="TextBox4" type="text" class="form-control" placeholder="Add" runat="server" Height="30px" Width="200px"></asp:TextBox>
        <asp:Button ID="Button5" class="btn btn-success" runat="server" Text="Register" OnClick="Button5_Click1" /> 
        <br/>
        <br/>
        <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover" Class="col-xs-12 col-md-8" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" DataKeyNames="Id" OnRowUpdating="GridView1_RowUpdating">
            <Columns>
                <asp:TemplateField InsertVisible="False" HeaderStyle-BackColor="#0000CC" FooterStyle-BackColor="#0000CC" ItemStyle-BackColor="#0000CC">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>' Visible="False"></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Id") %>' Visible="False"></asp:Label>
                    </ItemTemplate>

<FooterStyle BackColor="#0000CC"></FooterStyle>

<HeaderStyle BackColor="#0000CC"></HeaderStyle>

<ItemStyle BackColor="#0000CC"></ItemStyle>
                </asp:TemplateField>
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" ItemStyle-VerticalAlign="Middle" ItemStyle-HorizontalAlign="Center" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle">
<HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle"></HeaderStyle>

<ItemStyle HorizontalAlign="Center" VerticalAlign="Middle"></ItemStyle>
                </asp:BoundField>
                <asp:BoundField DataField="Lastname" HeaderText="Lastname" SortExpression="Lastname" />
                <asp:TemplateField HeaderText="Category And Cup" SortExpression="Category">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource2" DataTextField="Category" DataValueField="Category" SelectedValue='<%# Bind("Category") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Category") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Secundary Category" SortExpression="SecondCategory">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource3" DataTextField="Category" DataValueField="Category" SelectedValue='<%# Bind("SecondCategory") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("SecondCategory") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Camp" SortExpression="Camp">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource4" DataTextField="Choice" DataValueField="Choice" SelectedValue='<%# Bind("Camp") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Camp") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Price" HeaderText="€" ReadOnly="True" SortExpression="Price" />
            </Columns>

            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />

        </asp:GridView> 

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            DeleteCommand="DELETE FROM [T] WHERE [Id] = @original_Id" 
            InsertCommand="INSERT INTO [T] ([FirstName], [Lastname], [UserName], [Category], [SecondCategory], [Camp], [Price]) VALUES (@FirstName, @Lastname, @UserName, @Category, @SecondCategory, @Camp, @Price)" 
            OldValuesParameterFormatString="original_{0}" 
            SelectCommand="SELECT * FROM [T] WHERE ([UserName] = @UserName)"
            UpdateCommand="UPDATE [T] SET [FirstName] = @FirstName, [Lastname] = @Lastname, [Category] = @Category, [SecondCategory] = @SecondCategory, [Camp] = @Camp WHERE [Id] = @original_Id">
            <DeleteParameters>
                <asp:Parameter Name="original_Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="Lastname" Type="String" />
                <asp:Parameter Name="UserName" Type="String" />
                <asp:Parameter Name="Category" Type="String" />
                <asp:Parameter Name="SecondCategory" Type="String" />
                <asp:Parameter Name="Camp" Type="String"/>
                <asp:Parameter Name="Price" Type="Int32" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="DoNotTouch" Name="UserName" PropertyName="Text" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="Lastname" Type="String" />
                <asp:Parameter Name="Category" Type="String" />
                <asp:Parameter Name="SecondCategory" Type="String" />
                <asp:Parameter Name="Camp" Type="String" />
                <asp:Parameter Name="original_Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

</center>
        <br />

        <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            OldValuesParameterFormatString="original_{0}" 
            SelectCommand="SELECT [Category] FROM [SecondCategory]">
        </asp:SqlDataSource>


        <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            OldValuesParameterFormatString="original_{0}" 
            SelectCommand="SELECT [Category] FROM [Category]">
        </asp:SqlDataSource>


        <asp:SqlDataSource ID="SqlDataSource4" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            OldValuesParameterFormatString="original_{0}" 
            SelectCommand="SELECT [Choice] FROM [Camp]">
        </asp:SqlDataSource>


        <br />
        <br />
        <br />
    </section>
  </section>
    </form>
</asp:Content>
